title: Vincent<br/>van Gogh

logo: /assets/img/profile.jpg

description: I am a ..... at the University of ..... researching ....... <br/>
             <br/>
             <a href="https://scholar.google.co.uk/">ğŸ“ Google Scholar </a> <br/>
             <a href="https://fwilson93.github.io/template_website/assets/Vincent_van_Gogh_CV.pdf">ğŸ“ƒ CV </a>  <br/>
             <a href="https://environment.leeds.ac.uk/see/">ğŸ“ Leeds, UK </a>  <br/><br/>
            
             
show_downloads: false

# Google Analytics
google_analytics: true


theme: jekyll-theme-minimal
